### ISSUE TITLE
Make gh-pages default branch

### ISSUE THREAD

**Issue by nloveladyallen** [nlp-compromise/website#10]
No point in having a branch with just a README that tells you to go to gh-pages.

**Comment by spencermountain** [comment]
eep, it has a scarey message that i'm gonna hold-off on till we're off the github homepage :star2: 
![image](https://cloud.githubusercontent.com/assets/399657/15369563/2abd8230-1d01-11e6-95a5-383304d83445.png)
thanks for the good idea

**Comment by spencermountain** [comment]
done. let me know if you see anything silly from this
